joy_config:
  device_id: 0
  deadzone: 0.1
  autorepeat_rate: 10.0
  coalesce_interval_ms: 1

teleop:
  joy_config: "ps3"
  enable_button: 4  # L1 button
  enable_turbo_button: 5  # R1 button
  
  # Axis mapping for PS3 controller
  axis_linear:
    x: 1  # Left stick vertical
  axis_angular:
    yaw: 0  # Left stick horizontal
    
  # Scaling factors
  scale_linear: 0.3
  scale_linear_turbo: 0.6
  scale_angular: 0.5
  scale_angular_turbo: 1.0
  
  # Publishers
  cmd_vel_topic: "/cmd_vel"
