name: navcar-${USER}
services:
  emulator:
    image: tonistiigi/binfmt
    # container_name: emulator
    privileged: true
    command: --install arm64
    network_mode: bridge
    restart: "no"
  navcar-dev:
    depends_on:
      - emulator
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROXY_HOST=${PROXY_HOST:-host.docker.internal}
        - PROXY_PORT=${PROXY_PORT:-7890}
        - USER_UID=${USER_UID:-1000}
      platforms: 
        - linux/arm64
        #- linux/amd64
    image: navcar-dev:latest
    # container_name: navcar-dev-${USER:-dev}-${USER_UID:-1000}
    platform: linux/arm64

    # Enable GUI applications (for RViz, etc.)
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    volumes:
      # X11 forwarding for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

      - ../:/home/dev/workspace:rw
    devices:
      - /dev/input/js0:/dev/input/js0  # Map the joystick device
      - /dev/input/event1:/dev/input/event1
    network_mode: host
    tty: true
    stdin_open: true
    privileged: true
    user: dev
