base:
  mass: 3               # Base mass in Kg
  x_size: 0.69           # Dimension in x axis
  y_size: 0.315            # Dimension in y axis
  z_size: 0.102           # Dimension in z axis
  mesh: ''  # Name of the mesh files. Leave it empty ('') to have a white base.