teleop_twist_joy_node:
  ros__parameters:
    enable_button: 4  # L1 button
    enable_turbo_button: 5  # R1 button
    axis_linear.x: 1
    axis_angular.yaw: 3
    scale_linear.x: 0.3
    scale_linear_turbo.x: 0.6
    scale_angular.yaw: 0.5
    scale_angular_turbo.yaw: 1.0
    publish_stamped_twist: true